menu:
  Home: /
  Archives: archives

widgets:
- search
- category
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: 279078064
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 796581497680750
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
